---

version: "3.3"

services:

  nginx:
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    image: "gmir/docker-nginx:latest"
    container_name: nginx
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/nginx/config/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/config/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - appnet

  php:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: "gmir/docker-php-fpm:latest"
    container_name: php
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
      - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
    networks:
      - appnet

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: gmir/docker-node:latest
    container_name: node
    volumes:
      - ${APP_PATH}:${DOCUMENT_ROOT}
    networks:
          - appnet

  database:
    image: mysql:latest
    container_name: database
    restart: always
    volumes:
      - nginx_db_data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    networks:
      - appnet

networks:
  appnet:
    driver: "bridge"

volumes:
    nginx_db_data:
